# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gfiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(help_text='The reference to the uploaded data file', max_length=500, upload_to=gfiles.models.data_file_store)),
                ('original_filename', models.CharField(help_text='If a file with the same filename is uploaded at the same timea duplicate is saved with a unique name. This field is usedto keep track of the original name', max_length=500)),
                ('user', models.ForeignKey(help_text='The user who uploaded the file', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
