# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('gfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericfile',
            name='data_file',
            field=models.FileField(blank=True, help_text='The reference to the uploaded data file', max_length=500, null=True, upload_to=gfiles.models.data_file_store),
        ),
        migrations.AlterField(
            model_name='genericfile',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who uploaded the file', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
