# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gfiles', '0002_auto_20180817_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who uploaded the file', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
